version: "ole-{build}"

os: Windows Server 2012 R2
platform:
  - x64

cache:
  - vendor/bundle

clone_folder: c:\projects\win32-taskscheduler
clone_depth: 1

skip_commits:
  # version bumps by Expeditor happen as a separate commit after the merge, we can skip
  author: Chef Expeditor
  # if ONLY the files listed below are changed in a commit, skip
  files:
    - CHANGELOG.md

skip_tags: true
branches:
  only:
    - ole

environment:
  matrix:
    - ruby_version: "25-x64"
    - ruby_version: "25"
    - ruby_version: "24-x64"
    - ruby_version: "24"

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - bundle config --local path vendor/bundle # use the cache we define above

build_script:
  - bundle install || bundle install || bundle install

before_test:
  - ruby --version
  - gem --version
  - bundler --version
  - bundle env

test_script:
  - bundle exec rake
